extensions:
    pim-job-instance-sylake-akeneo-export-product-show:
        module: pim/form/common/edit-form

    pim-job-instance-sylake-akeneo-export-product-show-tabs:
        module: pim/form/common/form-tabs
        parent: pim-job-instance-sylake-akeneo-export-product-show
        targetZone: content
        position: 100

    pim-job-instance-sylake-akeneo-export-product-show-properties:
        module: pim/job/common/edit/properties
        parent: pim-job-instance-sylake-akeneo-export-product-show-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-job-instance-properties

    pim-job-instance-sylake-akeneo-export-product-show-history:
        module: pim/common/tab/history
        parent: pim-job-instance-sylake-akeneo-export-product-show-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 120
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: pim-job-instance-history

    pim-job-instance-sylake-akeneo-export-product-show-properties-code:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-sylake-akeneo-export-product-show-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    pim-job-instance-sylake-akeneo-export-product-show-properties-label:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-sylake-akeneo-export-product-show-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: true

    pim-job-instance-sylake-akeneo-export-product-show-label:
        module: pim/job/common/edit/label
        parent: pim-job-instance-sylake-akeneo-export-product-show
        targetZone: title
        position: 100

    pim-job-instance-sylake-akeneo-export-product-show-meta:
        module: pim/job/common/edit/meta
        parent: pim-job-instance-sylake-akeneo-export-product-show
        targetZone: meta
        position: 100

    pim-job-instance-sylake-akeneo-export-product-show-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: pim-job-instance-sylake-akeneo-export-product-show
        targetZone: back
        aclResourceId: pim_importexport_export_profile_index
        position: 80
        config:
            backUrl: pim_importexport_export_profile_index

    pim-job-instance-sylake-akeneo-export-product-show-edit:
        module: pim/common/redirect
        parent: pim-job-instance-sylake-akeneo-export-product-show
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_export_profile_edit
            identifier:
                path: code
                name: code

    pim-job-instance-sylake-akeneo-export-product-show-launch:
        module: pim/job/common/edit/launch
        parent: pim-job-instance-sylake-akeneo-export-product-show
        targetZone: buttons
        position: 110
        config:
            label: pim_enrich.form.job_instance.button.export.title
            route: pim_enrich_job_instance_rest_export_launch
            identifier:
                path: code
                name: code

    pim-job-instance-sylake-akeneo-export-product-show-content:
        module: pim/job/product/edit/content
        parent: pim-job-instance-sylake-akeneo-export-product-show-tabs
        aclResourceId: pim_importexport_export_profile_content_show
        targetZone: container
        position: 110
        config:
            tabTitle: pim_enrich.form.job_instance.tab.content.title
            tabCode: pim-job-instance-content

    pim-job-instance-sylake-akeneo-export-product-show-content-structure:
        module: pim/job/product/edit/content/structure
        parent: pim-job-instance-sylake-akeneo-export-product-show-content
        targetZone: structure-filters
        position: 100
        
    pim-job-instance-sylake-akeneo-export-product-show-content-structure-scope:
        module: pim/job/product/edit/content/structure/scope
        parent: pim-job-instance-sylake-akeneo-export-product-show-content-structure
        targetZone: filters
        position: 90
        config:
            readOnly: true

    pim-job-instance-sylake-akeneo-export-product-show-content-structure-locales:
        module: pim/job/product/edit/content/structure/locales
        parent: pim-job-instance-sylake-akeneo-export-product-show-content-structure
        targetZone: filters
        position: 100
        config:
            readOnly: true

    pim-job-instance-sylake-akeneo-export-product-show-content-data:
        module: pim/job/product/edit/content/data
        parent: pim-job-instance-sylake-akeneo-export-product-show-content
        targetZone: data-filters
        config:
            filters:
                -
                    field: enabled
                    view: akeneo-product-enabled-filter
                -
                    field: completeness
                    view: akeneo-product-completeness-filter

    pim-job-instance-sylake-akeneo-export-product-show-content-readonly:
        module: pim/job/product/edit/content/readonly
        parent: pim-job-instance-sylake-akeneo-export-product-show-content

    pim-job-instance-sylake-akeneo-export-product-show-content-data-help:
        module: pim/job/product/edit/content/data/help
        parent: pim-job-instance-sylake-akeneo-export-product-show-content-data        