extensions:
    pim-job-instance-sylake-akeneo-export-product-edit:
        module: pim/form/common/edit-form

    pim-job-instance-sylake-akeneo-export-product-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-job-instance-sylake-akeneo-export-product-edit
        position: 1000

    pim-job-instance-sylake-akeneo-export-product-edit-tabs:
        module: pim/form/common/form-tabs
        parent: pim-job-instance-sylake-akeneo-export-product-edit
        targetZone: content
        position: 100

    pim-job-instance-sylake-akeneo-export-product-edit-properties:
        module: pim/job/common/edit/properties
        parent: pim-job-instance-sylake-akeneo-export-product-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-job-instance-properties

    pim-job-instance-sylake-akeneo-export-product-edit-content:
        module: pim/job/product/edit/content
        parent: pim-job-instance-sylake-akeneo-export-product-edit-tabs
        aclResourceId: pim_importexport_export_profile_content_edit
        targetZone: container
        position: 110
        config:
            tabTitle: pim_enrich.form.job_instance.tab.content.title
            tabCode: pim-job-instance-content

    pim-job-instance-sylake-akeneo-export-product-edit-history:
        module: pim/common/tab/history
        parent: pim-job-instance-sylake-akeneo-export-product-edit-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 120
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: pim-job-instance-history

    pim-job-instance-sylake-akeneo-export-product-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-sylake-akeneo-export-product-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    pim-job-instance-sylake-akeneo-export-product-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-sylake-akeneo-export-product-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: false

    pim-job-instance-sylake-akeneo-export-product-edit-content-structure:
        module: pim/job/product/edit/content/structure
        parent: pim-job-instance-sylake-akeneo-export-product-edit-content
        targetZone: structure-filters
        position: 100

    pim-job-instance-sylake-akeneo-export-product-edit-label:
        module: pim/job/common/edit/label
        parent: pim-job-instance-sylake-akeneo-export-product-edit
        targetZone: title
        position: 100

    pim-job-instance-sylake-akeneo-export-product-edit-meta:
        module: pim/job/common/edit/meta
        parent: pim-job-instance-sylake-akeneo-export-product-edit
        targetZone: meta
        position: 100

    pim-job-instance-sylake-akeneo-export-product-edit-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: pim-job-instance-sylake-akeneo-export-product-edit
        targetZone: back
        aclResourceId: pim_importexport_export_profile_index
        position: 80
        config:
            backUrl: pim_importexport_export_profile_index

    pim-job-instance-sylake-akeneo-export-product-edit-delete:
        module: pim/job/export/edit/delete
        parent: pim-job-instance-sylake-akeneo-export-product-edit
        targetZone: buttons
        aclResourceId: pim_importexport_export_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.job_instance
                content: pim_enrich.confirmation.delete_item
                success: flash.job_instance.removed
                failed: error.removing.job_instance
            redirect: pim_importexport_export_profile_index

    pim-job-instance-sylake-akeneo-export-product-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: pim-job-instance-sylake-akeneo-export-product-edit
        targetZone: buttons
        position: 120

    pim-job-instance-sylake-akeneo-export-product-edit-save:
        module: pim/job-instance-export-edit-form/save
        parent: pim-job-instance-sylake-akeneo-export-product-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_export_profile_show

    pim-job-instance-sylake-akeneo-export-product-edit-state:
        module: pim/form/common/state
        parent: pim-job-instance-sylake-akeneo-export-product-edit
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.job_instance.title

    pim-job-instance-sylake-akeneo-export-product-edit-content-structure-scope:
        module: pim/job/product/edit/content/structure/scope
        parent: pim-job-instance-sylake-akeneo-export-product-edit-content-structure
        targetZone: filters
        position: 90

    pim-job-instance-sylake-akeneo-export-product-edit-content-structure-locales:
        module: pim/job/product/edit/content/structure/locales
        parent: pim-job-instance-sylake-akeneo-export-product-edit-content-structure
        targetZone: filters
        position: 100

    pim-job-instance-sylake-akeneo-export-product-edit-content-data:
        module: pim/job/product/edit/content/data
        parent: pim-job-instance-sylake-akeneo-export-product-edit-content
        targetZone: data-filters
        config:
            filters:
                -
                    field: enabled
                    view: akeneo-product-enabled-filter
                -
                    field: completeness
                    view: akeneo-product-completeness-filter

    pim-job-instance-sylake-akeneo-export-product-edit-validation:
        module: pim/job/common/edit/validation
        parent: pim-job-instance-sylake-akeneo-export-product-edit
